name: xapi CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: buildjet-4vcpu-ubuntu-2004
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.m2
        key: m2-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          m2-
    # - uses: DeLaGuardo/setup-graalvm@master
    #   with:
    #     graalvm-version: '21.3.0.java11'
    - uses: DeLaGuardo/setup-clojure@master
      with:
        tools-deps: '1.11.0.1100'
    # - run: gu install native-image
    # - run: make compile
    - run: make uber
    - name: "Generate tag"
      run: |
        COMMIT_DATE=$(git show -s --format=%cd --date=format:%y%m%d-%H%M HEAD)
        echo "tag_name=${COMMIT_DATE}" >> $GITHUB_ENV
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/xapi.jar
        asset_name: xapi.jar
        # file: xapi
        # asset_name: xapi-linux-amd64
        tag: ${{ env.tag_name }}
        overwrite: true
