name: xapi CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: ~/.m2
        key: m2-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          m2-
    # - uses: DeLaGuardo/setup-graalvm@master
    #   with:
    #     graalvm-version: '21.3.0.java11'
    - uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.11.1.1189'
    # - run: gu install native-image
    # - run: make compile
    - run: make uber
    - name: "Generate tag"
      run: |
        COMMIT_DATE=$(git show -s --format=%cd --date=format:%y%m%d-%H%M HEAD)
        echo "tag_name=${COMMIT_DATE}" >> $GITHUB_ENV
    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        files: target/xapi.jar
        tag_name: ${{ env.tag_name }}
